file_format: "1"
id: atreus3d
name: BFO-9000
type: shield
url: https://keeb.io/products/bfo-9000-keyboard-customizable-full-size-split-ortholinear
requires: [pro_micro]
features:
  - keys
siblings:
  - atreus3d_left
  - atreus3d_right
